// web/src/components/Header.vue
<template>
      <div class="tw-bg-indigo-500 tw-px-10 tw-gap-4 tw-py-2 md:tw-px-20 tw-flex tw-flex-col md:tw-flex-row tw-items-center tw-justify-between tw-w-full tw-text-white">
      <div class="tw-flex tw-gap-4 tw-items-center">
        <img class="tw-w-14 tw-h-14" src="../../static/logo.png" alt="logo da clina">
        <h1 class="tw-font-bold tw-text-white tw-m-0">Clinica veterinária</h1>
      </div>
      <a
        href="/user/signin"
        class="tw-flex tw-items-center tw-justify-center tw-gap-2 tw-font-bold tw-px-4 tw-py-2 tw-w-full tw-bg-indigo-700 md:tw-max-w-32 tw-rounded-lg"
      >
        <img src="../../static/user-icon.png" alt="user icon">
        Login
      </a>
    </div>
</template>

// ssr/components/Header.tsx
import Image from "next/image";

import Logo from "../assets/logo.png";

export function Header() {
  return (
    <div className="flex flex-col items-center justify-between py-2 px-10 w-full bg-indigo-500 text-white md:flex-row md:px-20">
      <div className="flex gap-4 items-center">
        <Image
          width={56}
          height={56}
          src={Logo}
          alt="logo da clina"
        />
        <h1 className="font-bold text-white text-3xl md:min-w-full">
          Clinica veterinária
        </h1>
      </div>

      <div>
        Nav...
      </div>
    </div>
  );
}
